
import {JetBrains_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/app/components/ui/Header";
import PageTransition from "@/app/components/ui/PageTransition";
import StairTransition from "@/app/components/ui/StairTransition";

const jetbrainsMono = JetBrains_Mono({ subsets: ["latin"], weight: ["100","200","300","400","500","600","700","800"], 
  variable:'--font-jetbrainsMono'
}); 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ReactNode } from "react";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={jetbrainsMono.variable}
      >
        <Header />
        <StairTransition />
        <PageTransition>

        {children}
        </PageTransition>
      </body>
    </html>
  );
}
